### ISSUE TITLE
mobile webform edits

### ISSUE THREAD

**Issue by jenbrannstrom** [stageflagmediallc/hipotecarias#1]
[This](https://hipotecarias.us/contacto-por-snapchat-numero_001.html) webform

Is meant only for mobile traffic.
It needs to all fit onto one screen - no scrolling
1. Fields need to be large and easy to type in. HTML5 form fields "[input type](https://diveintohtml5.info/forms.html)" need to be added
so that the correct keyboard gets pulled up.
2. Autofocus should be on Name field
3. ALL code removed that does nothing
4. It requires these fields:
Name *required 
phone *required 
email (optional)
5. at the top should go [this video](https://www.youtube.com/watch?v=Hb9CaUZNnTk&feature=youtu.be)
6. language settings = Spanish 
7. get rid of jquery if you can 
8. get rid of all external styling, js, etc that are not essential
9. _try_ to keep the look & feel of the form, but it's not essential

**Comment by polasrahman** [comment]
What will happen if visit this page on the desktop?
