### ISSUE TITLE
snap pixel

### ISSUE THREAD

**Issue by jenbrannstrom** [stageflagmediallc/hipotecarias#10]
Please add the snap pixel to the thankyou page
This one with 'snaptr('track', 'SIGN_UP');'

'
<script type='text/javascript'>
(function(e,t,n){if(e.snaptr)return;var a=e.snaptr=function()
{a.handleRequest?a.handleRequest.apply(a,arguments):a.queue.push(arguments)};
a.queue=[];var s='script';r=t.createElement(s);r.async=!0;
r.src=n;var u=t.getElementsByTagName(s)[0];
u.parentNode.insertBefore(r,u);})(window,document,
'https://sc-static.net/scevent.min.js');

snaptr('init', '3b573840-4ec0-48ed-bc78-2884ba970387', {
'user_email': '__INSERT_USER_EMAIL__'
});

snaptr('track', 'SIGN_UP');

</script>
'

**Comment by jenbrannstrom** [comment]
@aviox-git 
Doc: https://businesshelp.snapchat.com/en-US/a/purchase-event

**Comment by aviox-git** [comment]
on the contact form i was sending user email address in snap pixel. So what email address i will use on thank you page
__INSERT_USER_EMAIL__

**Comment by jenbrannstrom** [comment]
We need to register when someone submitted their details, or when they clicked "call".
If we can do that, then we don't need to have a pixel on the thank you page
