### ISSUE TITLE
remove other client data

### ISSUE THREAD

**Issue by jenbrannstrom** [stageflagmediallc/hipotecarias#11]
Please keep customers completely separate:

https://i.imgur.com/SibX0f5.jpg

Please remove all these calls of other client data

**Comment by aviox-git** [comment]
This code is not working. this is comment and not in running state. I will also remove the lines too

**Comment by jenbrannstrom** [comment]
yes, please just remove these links, etc
We need to keep a clean ship ;)

**Comment by aviox-git** [comment]
Done
