### ISSUE TITLE
form submits with 0 data

### ISSUE THREAD

**Issue by jenbrannstrom** [stageflagmediallc/hipotecarias#12]
simply clicking "submit" or "call later" on this p[age:
https://hipotecarias.us/contacto-por-snapchat-numero_001.html
results in a redirect to thankyou page.
Instead of this it should require data fields to be filled in before submitting

**Comment by aviox-git** [comment]
Done

**Comment by jenbrannstrom** [comment]
You need to COMMIT the changes to Git
https://i.imgur.com/fXXcofP.jpg

**Comment by aviox-git** [comment]
done

**Comment by jenbrannstrom** [comment]
The call me later button still has this issue

**Comment by aviox-git** [comment]
Fixed on call me later button too
