### ISSUE TITLE
call button & script

### ISSUE THREAD

**Issue by jenbrannstrom** [stageflagmediallc/hipotecarias#2]
add a Call Now button above the webform - centre page

add this script, which calls a dynamic phone number to be placed in the button
`<script> (function(e,d) {
        //Ringba.com phone number tracking
        var ringba_com_tag="JS59799af737a741b5a1777212d2c84992";
        var _sc = d.getElementsByTagName('script'), _s = _sc[_sc.length - 1];
        e._rgba = e._rgba || { q: [] }; e._rgba.q.push({ tag: ringba_com_tag, script: _s });
        if (!(e._rgba.loading = !!e._rgba.loading)) {
            var sc = d.createElement('script'); sc.type = 'text/javascript'; sc.async = true;
            sc.src = '//js.callcdn.com/js_v2/min/ringba.com.js';
            var s = d.getElementsByTagName('script')[0]; s.parentNode.insertBefore(sc, s);
            e._rgba.loading = true;
        }
   })(window,document); </script>`

**Comment by polasrahman** [comment]
button and script added. don't know how the script works

**Comment by jenbrannstrom** [comment]
@polasrahman check this doc:
https://www.ringba.com/support/ringba-js-basic-integration
or
https://www.ringba.com/support/ringba-js-advanced-integration

**Comment by polasrahman** [comment]
above Ringba id incorrect.
Show this message:
404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.

**Comment by jenbrannstrom** [comment]
@polasrahman 

I will speak with Ringba support
How / where do you get that error msg?

**Comment by polasrahman** [comment]
I placed the code as your ringba reference link.
When don't show any number or text then i follow this step to check the id.
<script src="//js.callcdn.com/dist/ringba.com.js?c=JS59799af737a741b5a1777212d2c84992"></script>
No output from here....
If you go the direct link you can understand. 
Thanks

**Comment by jenbrannstrom** [comment]
@polasrahman I have sent it to their helpdesk

**Comment by jenbrannstrom** [comment]
`<script> (function(e,d) {
        //Ringba.com phone number tracking
        var ringba_com_tag="JS59799af737a741b5a1777212d2c84992";
        var _sc = d.getElementsByTagName('script'), _s = _sc[_sc.length - 1];
        e._rgba = e._rgba || { q: [] }; e._rgba.q.push({ tag: ringba_com_tag, script: _s });
        if (!(e._rgba.loading = !!e._rgba.loading)) {
            var sc = d.createElement('script'); sc.type = 'text/javascript'; sc.async = true;
            sc.src = '//js.callcdn.com/js_v2/min/ringba.com.js';
            var s = d.getElementsByTagName('script')[0]; s.parentNode.insertBefore(sc, s);
            e._rgba.loading = true;
        }
   })(window,document); </script>`


> same code without github comment symbol

<script> (function(e,d) {
        //Ringba.com phone number tracking
        var ringba_com_tag="JS59799af737a741b5a1777212d2c84992";
        var _sc = d.getElementsByTagName('script'), _s = _sc[_sc.length - 1];
        e._rgba = e._rgba || { q: [] }; e._rgba.q.push({ tag: ringba_com_tag, script: _s });
        if (!(e._rgba.loading = !!e._rgba.loading)) {
            var sc = d.createElement('script'); sc.type = 'text/javascript'; sc.async = true;
            sc.src = '//js.callcdn.com/js_v2/min/ringba.com.js';
            var s = d.getElementsByTagName('script')[0]; s.parentNode.insertBefore(sc, s);
            e._rgba.loading = true;
        }
   })(window,document); </script>

**Comment by jenbrannstrom** [comment]
support says this is the file location: js.callcdn.com/js_v2/min/ringba.com.js
Which works
The one you sent,  I assume is just a variable that is only valid when the JS file has been loaded

**Comment by jenbrannstrom** [comment]
@polasrahman ringba support sent me a corrected code
It now adds the number dynamically
But it's placing it in the wrong place and breaking the page: https://prnt.sc/n4oi3f

Please can you correct the HTML?

**Comment by aviox-git** [comment]
VM87:1 POST https://display.ringba.com/v1/nis/gn 404 (Not Found)

**Comment by aviox-git** [comment]
getting above error on console. When running ringa script

**Comment by aviox-git** [comment]
Task is done
