### ISSUE TITLE
fields markup

### ISSUE THREAD

**Issue by jenbrannstrom** [stageflagmediallc/hipotecarias#3]
The webform fields on [this page](https://github.com/stageflagmediallc/hipotecarias/blob/master/contacto-por-snapchat-numero_001.html)
Shoudl be marked-up with the labels shown [here](https://businesshelp.snapchat.com/en-US/a/auto-fill)
please add fields:
first name
last name
phone
email
zip

**Comment by polasrahman** [comment]
Done
