### ISSUE TITLE
additional fields

### ISSUE THREAD

**Issue by jenbrannstrom** [stageflagmediallc/hipotecarias#4]
using the design of the contact form CSS, please add the following:

TWO buttons
and a layout like this: https://i.imgur.com/40BQu0y.jpg

the "Call Now" button, should contain a call script
the "Call me later please" button submits the form.
the form should prepopulate, as per the issue [fields markup](https://github.com/stageflagmediallc/hipotecarias/issues/3)

**Comment by aviox-git** [comment]
Please provide number for call now option.
Is form currently submitting data somewhere or need to add crm webform like other pages?

**Comment by jenbrannstrom** [comment]
> Please provide number for call now option.

This is covered under[ separate issue, using a script](https://github.com/stageflagmediallc/hipotecarias/issues/2)

> Is form currently submitting data somewhere or need to add crm webform like other pages?

Yes, should submit to Google sheet, also in [separate issue](https://github.com/stageflagmediallc/hipotecarias/issues/5)

**Comment by polasrahman** [comment]
extra field added

**Comment by jenbrannstrom** [comment]
please fix this: http://prntscr.com/n3murg

**Comment by polasrahman** [comment]
fixed
