### ISSUE TITLE
connect webform to Google sheet

### ISSUE THREAD

**Issue by jenbrannstrom** [stageflagmediallc/hipotecarias#5]
using the same JS technique shown here:

1. use a Google sheet, like [this one](https://docs.google.com/spreadsheets/d/1fxBtaHz6DpUplediYZAOJeio_XUYn_45wTFsTFFdE0A/edit#gid=1443838378)
2. clone the JS scripts "notify.js" & "oca_submit.js" found [here](https://github.com/qualifiedleads/oca-bxl/tree/gh-pages/js)
3. edit the sheet ID's in those files
4. clone the JS script below and add it to the [Google sheets Script editor](https://i.imgur.com/aVcQdPv.jpg)

`function doGet(e) {
  var data  = e.parameter;
  var ss    = SpreadsheetApp.openByUrl('https://docs.google.com/spreadsheets/d/1fxBtaHz6DpUplediYZAOJeio_XUYn_45wTFsTFFdE0A/edit#gid=1443838378');
  var sheet = ss.getSheetByName('Active');
  
  var fname  = data.fname;
  var lname  = data.lname;
  var email  = data.email;
  var age    = data.age;
  var gender = data.gender;
  var phone  = data.phone;
  var origin = data.origin;
  var country = data.countryname;
  var zip = data.zipcode;
  var date = Utilities.formatDate(new Date(), "CET", "yyyy-MM-dd hh:mm:ss a z");
  
  sheet.appendRow([fname,lname,email,age,gender,phone,date,country,zip,origin]);
  
  var reply  = {status:"ok",message:"Data successfully written to sheets."};
  
  return ContentService.createTextOutput(JSON.stringify(reply))
         .setMimeType(ContentService.MimeType.JAVASCRIPT);
}`

**Comment by jenbrannstrom** [comment]
@polasrahman 
Please use this G Sheet
https://docs.google.com/spreadsheets/d/1yBIU4AF6lrVo18oIqk1WDBRztCwia4UOCnKg2cUvFCQ/edit?usp=sharing

**Comment by polasrahman** [comment]
I can not understand this.
I am not familiar with this.
Help me please

**Comment by jenbrannstrom** [comment]
@polasrahman 
let me try.. :)

1. open [this sample sheet](https://docs.google.com/spreadsheets/d/1fxBtaHz6DpUplediYZAOJeio_XUYn_45wTFsTFFdE0A/edit#gid=1443838378)
2. in that Google sheet go to Tools --> Script Editor (see the code there)
3. copy that code into the script editor for [THIS NEW SHEET](https://docs.google.com/spreadsheets/d/1yBIU4AF6lrVo18oIqk1WDBRztCwia4UOCnKg2cUvFCQ/edit?usp=sharing)
4. clone the JS scripts "notify.js" & "oca_submit.js" found here
5. edit the sheet ID's in "notify.js" & "oca_submit.js"
